#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by CMake (smtg_target_configure_version_file).
#include "projectversion.h"

#define stringOriginalFilename "HyraxLimiter.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Hyrax Limiter VST3 (64Bit)"
#else
#define stringFileDescription "Hyrax Limiter VST3"
#endif
#define stringCompanyName "Code of the Geeks\0"
#define stringLegalCopyright "Copyright(c) 2026 Jasper Schrader"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
